spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: shops-service
          uri: lb://shops-service
          predicates:
            - Path=/api/shops/**
          filters:
            - StripPrefix=2
        - id: purchase-service
          uri: lb://purchase-service
          predicates:
            - Path=/api/purchase/**
          filters:
            - StripPrefix=2

    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instanceId: ${spring.application.name}:${random.uuid}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka